---
- hosts: proxy
  become: true

  tasks:

   - name: Include Vars File
     include_vars: ./vars.yml

   - name: Update Repositories
     apt:
      update_cache: yes
   - name: Install Required System Packages
     apt:
      pkg:
       - apt-transport-https
       - ca-certificates
       - curl
       - software-properties-common
       - python3-pip=20.3.4-4+deb11u1
       - virtualenv=20.4.0+ds-2+deb11u1
       - python3-setuptools=52.0.0-4
       - gnupg=2.2.27-2+deb11u2
       - lsb-release=11.1.0
      state: present

   - name: Remove Old Key Docker Files
     ansible.builtin.file:
       path: /etc/apt/keyrings/docker.gpg
       state: absent

   - name: Remove Old Source Docker Files
     ansible.builtin.file:
       path: /etc/apt/sources.list.d/docker.list
       state: absent

   - name: Create Directory For keyrings
     file:
      path: /etc/apt/keyrings
      state: directory

   - name: Add Docker GPG apt Key
     shell: 'curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg'

   - name: Add Docker Repository
     shell: 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null'

   - name: Update Repositories After Docker Repository
     apt:
      update_cache: yes

   - name:  Install Docker-ce
     apt:
      name: "docker-ce={{docker_version}}"


   - name: Create Network
     docker_network:
       name: vira

   - name: Include Unbound Task
     include_tasks: unbound.yml

   - name: Include Nginx Task
     include_tasks: nginx.yml
